# Generated by Django 2.1.5 on 2022-02-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20220219_1917'),
        ('rango', '0003_category_slug'),
    ]

    operations = [
    ]
